project:
  type: book
  output-dir: "../rendered_documents"

book:
  output-file: "Ambiguity attitudes and surprises: Computational reproduction"

  title: "Ambiguity attitudes and surprises"
  subtitle: "Computational reproduction"
  author:
  - name: Aljoscha Minnich
    email: aljoscha.minnich@uni-hamburg.de
    orcid: 0000-0001-5224-0143
    corresponding: false
    affiliations:
      - name: Center for Earth System Research and Sustainability (CEN), University of Hamburg
        address: Bundesstrasse 53
        city: Hamburg
        country: Germany
        postal-code: 20146
      - name: Department of Economics, University of Hamburg
        address:  Von-Melle-Park 5
        city: Hamburg
        country: Germany
        postal-code: 20146
  - name: Hauke Roggenkamp
    email: Hauke.Roggenkamp@unisg.ch
    orcid: 0009-0005-5176-4718
    corresponding: false
    affiliations:
      - name: Institute of Behavioral Science and Technology, University of St. Gallen
        address: Torstrasse 25
        city: St. Gallen
        country: Switzerland
        postal-code: 9000
      - name: Faculty of Economics & Social Sciences, Helmut-Schmidt-University
        address: Holstenhofweg 85
        city: Hamburg
        country: Germany
        postal_code: 22043
  - name: Andreas Lange
    email: andreas.lange@uni-hamburg.de
    corresponding: true
    affiliations:
      - name: Center for Earth System Research and Sustainability (CEN), University of Hamburg
        address: Bundesstrasse 53
        city: Hamburg
        country: Germany
        postal-code: 20146
      - name: Department of Economics, University of Hamburg
        address:  Von-Melle-Park 5
        city: Hamburg
        country: Germany
        postal-code: 20146
  date: now
  chapters:
    - index.qmd
    - 01-pre-processing.qmd
    - part: "Main Body"
      chapters:
        - 02-tables.qmd
        - 03-figures.qmd
    - part: "Appendix"
      chapters:
        - 04-appendix-A.qmd
        - 05-appendix-B.qmd
        - 06-appendix-C.qmd
        - 07-appendix-D.qmd
    - part: "Online Appendix"
      chapters:
        - A-online-appendix.qmd
        - B-online-appendix.qmd
        - C-online-appendix.qmd
        - D-online-appendix.qmd
        - E-online-appendix.qmd
    - X-references.qmd
  appendices:
    - X-session-info.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    embed-resources: true
    execute:
      warning: false
  # pdf:
  #   execute:
  #     echo: false
  #     warning: false
  #   documentclass: scrreprt
  #   keep-tex: true
  #   toc: true
  #   toc-depth: 3
  #   toc-title: "Table of contents"
  #   lof: false
  #   lot: false
  #   number-sections: true
  #   number-depth: 2
  #   papersize: a4
  #   indent: true
  #   include-in-header: include-in-header.tex
  #   template-partials:
  #     - before-body.tex
    
   