# Preface {.unnumbered}

This document provides a step-by-step guide to reproducing the figures and tables presented in @MinnichEtAl_2023, using a literate programming approach [@Knuth_1984]. By combining some narrative explanations with code and its output, we aim to increase our analyses' transparency and reproducibility, allowing other researchers to validate, modify, and extend our findings. Whereas the reproduction captures the substance of all results, minor discrepancies in the style of some tables and figures may arise due to post-processing in LaTeX and the fact that this document generates HTML output rather than PDF. These differences do not affect the accuracy or interpretation of the findings.

Beneath each script, we print its session information, which provides a record of the R environment, including package versions and system details.^[Whenever we report clustered standard errors, we calculated them using the `{sandwich}` packages by @Zeileis_2004 and @ZeileisEtAl_2020.] This ensures that others can replicate the analysis under the same conditions, reducing the risk of discrepancies due to software version differences. In addition, we use `{groundhog}` as a package versioning tool to maintain consistent and reproducible package versions.

The following is the BibTeX entry for the key reference, which can be used to cite our paper in future research or to replicate the results:

```bibtex
@article{MinnichEtAl_2023,
  title = {Ambiguity Attitudes and Surprises: Experimental Evidence on Communicating New Information within a Large Population Sample},
  author = {Minnich, Aljoscha and Roggenkamp, Hauke and Lange, Andreas},
  year = {2023},
  type = {CESifo Working Paper},
  number = {10783},
  institution = {CESifo},
  doi = {10.2139/ssrn.4646369},
  url = {https://ssrn.com/abstract=4646369}
}
```


## R Version Disclaimer

This reproduction package was developed using R version 4.4.1 (2024-06-14). To ensure the most accurate replication of results, it is recommended to use this specific R version.
If you are using a different R version, you have two options:

1. Install R version 4.4.1 (2024-06-14) to match the original environment.
2. Adjust the date in the `groundhog.library()` function call (at the beginning of every script) to find a date that is compatible with your R version. The current code uses the following setup:

```{r}
#| echo: true
#| eval: false

options(repos = c(CRAN = "https://cran.r-project.org")) 
if (!requireNamespace("groundhog", quietly = TRUE)) {
    install.packages("groundhog")
}
pkgs <- c("magrittr", "data.table", "stringr", "lubridate", "glue", "knitr")
groundhog::groundhog.library(pkg = pkgs,
                             date = "2024-08-01")
rm(pkgs)
```

If you need to adjust the date, modify the date parameter in the `groundhog.library()` function. Choose a date that is compatible with your R version and ensures all required packages are available.

Please note that using a different R version or package versions may potentially lead to slight differences in results. If you encounter any issues or discrepancies, consider installing the recommended R version for the most accurate replication.

## References {-}